[package]
name = "ennio_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonschema = "0.16"
log = "0.4"
regex = "1.5"
serde_json = "1.0"
serde_yaml = "0.8"
